[package]
name = "trapped_in_the_realm_of_generosity_dataport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
sqlx = {version = "0.7.2", features = ["postgres"]}
