version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '15432:5432'
    volumes:
      - postgresDB:/var/lib/mysql
volumes:
  postgresDB: